name: Build and Test

on: 
  workflow_dispatch:
    inputs:
      failJob:
        description: Fail the job?
        type: boolean
        required: true
        default: false

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v1
    
    - name: Setup python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    
    - name: Run app
      run: python app.py
    
    - name: Run tests
      run: python tests.py
    
    - name: Pass or fail job
      run: exit 1
      if: github.event.inputs.failJob == 'true'
