name: Build and Test

on: 
  workflow_dispatch

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v1
    
    - name: Setup python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    
    - name: Run app
      run: python app.py
    
    - name: Run tests
      run: python tests.py
